runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        cache: yarn
        cache-dependency-path: nuxt/yarn.lock
    - run: yarn install
      shell: bash
