name: Node CI
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - staging
env:
  node-version: 16.15.1
defaults:
  run:
    shell: bash
    working-directory: ./nuxt
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initialize
        uses: ./.github/actions/initialize
      - name: lint
        run: yarn run lint
  unit:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initialize
        uses: ./.github/actions/initialize
      - name: unit test run
        run: yarn run test
  # e2e:
  #   name: E2E test
  #   runs-on: self-hosted
  #   needs: lint
  #   if: success()
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ env.node-version }}
  #         cache: yarn
  #     - run: yarn install
  #     - name: e2e test run
  #       run: |
  #         echo ${{ secrets.ENV_TEST }} | base64 -d > .env
  #         yarn run test:e2e
