name: Node CI
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
env:
  node-version: 16.15.1
jobs:
  lint:
    name: Lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - run: cd nuxt/
      - run: yarn install
      - name: lint
        run: yarn run lint
  unit:
    name: Unit test
    runs-on: self-hosted
    needs: lint
    if: success()
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - run: yarn install
      - name: unit test run
        run: |
          echo ${{ secrets.ENV_TEST }} | base64 -d > .env
          yarn run test
  e2e:
    name: E2E test
    runs-on: self-hosted
    needs: lint
    if: success()
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - run: yarn install
      - name: e2e test run
        run: |
          echo ${{ secrets.ENV_TEST }} | base64 -d > .env
          yarn run test:e2e
